name: GSVAanalysis
output_dir: "docs"
navbar:
  title: "GSVA analysis of spatial transcriptomics data"
  left:
    - text: "Home"
      href: index.html
    - text: "QA & processing mouse brain data"
      href: docs/01_qa_pr_mouse.html
    - text: "GSVA analysis mouse brain data"
      href: 02_gsva_mouse.html
    - text: "QA & processing human DLPFC data"
      href: 03_qa_pr_hdlpfc.html
    - text: "GSVA analysis human DLPFC data"
      href: 04_gsva_hdlpfc.html
output:
  BiocStyle::html_document:
    toc: true
    toc_float: true
    number_sections: true
    fig_captions: yes
    theme: cosmo

